// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrdswhlcgkscxnzdblhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZHN3aGxjZ2tzY3huemRibGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTgyNDYsImV4cCI6MjA2MTE3NDI0Nn0.DR16Ed1_OgdY69fXIrMKlt04d_QTQFhXxrHIHUMZYE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);